/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'appointmentTime' : IDL.Nat,
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
  'mobile' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'clinicName' : IDL.Text,
});
export const Time = IDL.Int;
export const Lead = IDL.Record({
  'doctorRemark' : IDL.Text,
  'leadName' : IDL.Text,
  'addToAppointment' : IDL.Bool,
  'area' : IDL.Text,
  'treatmentWanted' : IDL.Text,
  'rating' : IDL.Nat8,
  'mobile' : IDL.Text,
  'expectedTreatmentDate' : IDL.Int,
  'followUpDate' : IDL.Int,
});
export const Patient = IDL.Record({
  'area' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Nat8,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'addPatient' : IDL.Func(
      [IDL.Opt(ExternalBlob), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAppointment' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'deleteLead' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deletePatient' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLastModified' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getLastModifiedAppointments' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getLastModifiedLeads' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getLastModifiedPatients' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getLastModifiedProfile' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getLastModifiedTimes' : IDL.Func(
      [],
      [
        IDL.Record({
          'leads' : IDL.Opt(Time),
          'appointments' : IDL.Opt(Time),
          'patients' : IDL.Opt(Time),
          'profile' : IDL.Opt(Time),
        }),
      ],
      ['query'],
    ),
  'getLastSyncTime' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getTodaysAppointmentsSorted' : IDL.Func(
      [],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getTomorrowAppointmentsSorted' : IDL.Func(
      [],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getUpcomingAppointmentsSorted' : IDL.Func(
      [],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Text], []),
  'register' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppointment' : IDL.Func([IDL.Nat, Appointment], [IDL.Text], []),
  'updateLastSyncTime' : IDL.Func([], [], []),
  'updateLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Nat8,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'updatePatient' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'appointmentTime' : IDL.Nat,
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'clinicName' : IDL.Text,
  });
  const Time = IDL.Int;
  const Lead = IDL.Record({
    'doctorRemark' : IDL.Text,
    'leadName' : IDL.Text,
    'addToAppointment' : IDL.Bool,
    'area' : IDL.Text,
    'treatmentWanted' : IDL.Text,
    'rating' : IDL.Nat8,
    'mobile' : IDL.Text,
    'expectedTreatmentDate' : IDL.Int,
    'followUpDate' : IDL.Int,
  });
  const Patient = IDL.Record({
    'area' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Nat8,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'addPatient' : IDL.Func(
        [IDL.Opt(ExternalBlob), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAppointment' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'deleteLead' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deletePatient' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLastModified' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getLastModifiedAppointments' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getLastModifiedLeads' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getLastModifiedPatients' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getLastModifiedProfile' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getLastModifiedTimes' : IDL.Func(
        [],
        [
          IDL.Record({
            'leads' : IDL.Opt(Time),
            'appointments' : IDL.Opt(Time),
            'patients' : IDL.Opt(Time),
            'profile' : IDL.Opt(Time),
          }),
        ],
        ['query'],
      ),
    'getLastSyncTime' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getTodaysAppointmentsSorted' : IDL.Func(
        [],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getTomorrowAppointmentsSorted' : IDL.Func(
        [],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getUpcomingAppointmentsSorted' : IDL.Func(
        [],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Text], []),
    'register' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppointment' : IDL.Func([IDL.Nat, Appointment], [IDL.Text], []),
    'updateLastSyncTime' : IDL.Func([], [], []),
    'updateLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Nat8,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'updatePatient' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };