/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'appointmentTime' : bigint,
  'notes' : string,
  'patientName' : string,
  'mobile' : string,
}
export type ExternalBlob = Uint8Array;
export interface Lead {
  'doctorRemark' : string,
  'leadName' : string,
  'addToAppointment' : boolean,
  'area' : string,
  'treatmentWanted' : string,
  'rating' : number,
  'mobile' : string,
  'expectedTreatmentDate' : bigint,
  'followUpDate' : bigint,
}
export interface Patient {
  'area' : string,
  'name' : string,
  'notes' : string,
  'image' : [] | [ExternalBlob],
  'mobile' : string,
}
export type Time = bigint;
export interface UserProfile { 'username' : string, 'clinicName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppointment' : ActorMethod<[string, string, bigint, string], string>,
  'addLead' : ActorMethod<
    [string, string, string, string, bigint, bigint, number, string, boolean],
    string
  >,
  'addPatient' : ActorMethod<
    [[] | [ExternalBlob], string, string, string, string],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAppointment' : ActorMethod<[bigint], string>,
  'deleteLead' : ActorMethod<[string], string>,
  'deletePatient' : ActorMethod<[string], string>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLastModified' : ActorMethod<[], [] | [Time]>,
  'getLastModifiedAppointments' : ActorMethod<[], [] | [Time]>,
  'getLastModifiedLeads' : ActorMethod<[], [] | [Time]>,
  'getLastModifiedPatients' : ActorMethod<[], [] | [Time]>,
  'getLastModifiedProfile' : ActorMethod<[], [] | [Time]>,
  'getLastModifiedTimes' : ActorMethod<
    [],
    {
      'leads' : [] | [Time],
      'appointments' : [] | [Time],
      'patients' : [] | [Time],
      'profile' : [] | [Time],
    }
  >,
  'getLastSyncTime' : ActorMethod<[], [] | [Time]>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getPatients' : ActorMethod<[], Array<Patient>>,
  'getTodaysAppointmentsSorted' : ActorMethod<[], Array<Appointment>>,
  'getTomorrowAppointmentsSorted' : ActorMethod<[], Array<Appointment>>,
  'getUpcomingAppointmentsSorted' : ActorMethod<[], Array<Appointment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, Uint8Array], string>,
  'register' : ActorMethod<[string, Uint8Array], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppointment' : ActorMethod<[bigint, Appointment], string>,
  'updateLastSyncTime' : ActorMethod<[], undefined>,
  'updateLead' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      number,
      string,
      boolean,
    ],
    string
  >,
  'updatePatient' : ActorMethod<
    [string, [] | [ExternalBlob], string, string, string, string],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];